development:
  database: social_media
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: social_media_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db